### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by anchikai**
Updated loom to 1.2 and changed versioning, thats about it. No 1.20 branch to target, so 🤷‍♀️

### CODE REVIEW

**Comment by milkev** [comment]
Can confirm this works, have not done extensive testing but it seems to be working fine for me

**Comment by Jaytche** [comment]
Can we get one for 1.20.1? mine doesnt seem to work for it.

**Comment by anchikai** [comment]
> Can we get one for 1.20.1? mine doesnt seem to work for it.

I committed a microscopic change that should make it compatible with 1.20.1, tho I didn't test it so lmk if it doesn't work.

**Comment by MoriyaShiine** [comment]
Will this be merged any time soon? I rely on it for 3 mods

**Comment by milkev** [comment]
> Will this be merged any time soon? I rely on it for 3 mods

If you can build the branch successfully (like i did) you can just embed it in your mod. Worked for me & my mod.
I just had to add a flat dir since their online repository doesnt have the .jar file. you can view my [build.gradle](https://github.com/milkev/Milkevs-Essentials/commit/64f45483a7638af4d5e36e59d94ad620d4391533?diff=unified#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7) for how i did it if you want.

**Comment by ChloeDawn** [comment]
2.4.0 is now available on the Maven

**Pull request merged**
