### PR TITLE
Add Forge compatibility

### PR DESCRIPTION
**Pull request by Sollace**
This makes is so the game will no longer crash when loading with Forge/Neo via Synatra Connector.

I just exclude all the mixins except essential ones add a new mixin into IForgePlayer#getBlockReach and IForgePlayer#getEntityReach so this mod's version of the attributes are still applied.

Also included is #35 to port to 1.20.4 as I needed that in my build.

### CODE REVIEW

**Comment by Sollace** [comment]
Build for those who want to test it/need it: https://github.com/Sollace/reach-entity-attributes/releases/tag/2.4.2

**Comment by ChloeDawn** [comment]
Can you explain why one mixin class is always applied? What makes it mandatory over others when Forge is present?

**Comment by Sollace** [comment]
> Can you explain why one mixin class is always applied? What makes it mandatory over others when Forge is present?

That one is to register the attributes used by reach-entity-attributes. I didn't want to rewrite everything to get it to use forge's attribute. That would have been too much work and make it very hard to have something that still builds in a plain fabric environment without doing some magic with loom gradle.

**Comment by Sollace** [comment]
It's not super important if you don't want to merge this I figure, since with 1.20.5 mojang is adding their own attribute. I figured it would useful for other people.

**Comment by ChloeDawn** [comment]
As I have already merged the 1.20.4 pull request, this one conflicts. I'll implement it myself but I appreciate the contribution ❤️

**Comment by ChloeDawn** [comment]
On further research, it seems Sinytra has already added compatibility for Reach Entity Attributes on their end, in the form of [a reimplementation in ConnectorExtras](https://github.com/Sinytra/ConnectorExtras/tree/5b22b019f3027067e8f0771ba7f7cf542b659296/reach-entity-attributes)

**Pull request closed without merging**
