### PR TITLE
Bump versions and finalize for 1.20.1

### PR DESCRIPTION
**Pull request by ghost**
- Required making a static method non-static
- Bumped versions in gradle.properties and fabric.mod.json
- All appeared to be working when I briefly tested it, though it would be a good idea to check it before merging if you review this PR

That's about it :D

### CODE REVIEW

**Comment by ChloeDawn** [comment]
2.5.0 should be compatible with 1.20.1, if it's not please let me know. The changes in this pull request are already covered by that release

**Comment by ChloeDawn** [comment]
Actually, it won't be compatible because I declared a dependency on 1.20.4 in the metadata. I will resolve this later tonight

**Comment by cph101** [comment]
Yeah, throws these:
image


The funny thing is that the project using my branch appeared to work in the IDE and ran fine by using the context menu, but running it after building resulted in a ClassNotFoundException?

**Comment by ghost** [comment]
If you're wondering where my previous comment went I deleted it because I didn't realise it disclosed my personal information

**Comment by crehop** [comment]
so are you just not going to post a 1.20.1 branch ? or was this commit just missed?

**Pull request closed without merging**
